// Generated by gencpp from file rob1514/NavPoint.msg
// DO NOT EDIT!


#ifndef ROB1514_MESSAGE_NAVPOINT_H
#define ROB1514_MESSAGE_NAVPOINT_H

#include <ros/service_traits.h>


#include <rob1514/NavPointRequest.h>
#include <rob1514/NavPointResponse.h>


namespace rob1514
{

struct NavPoint
{

typedef NavPointRequest Request;
typedef NavPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NavPoint
} // namespace rob1514


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rob1514::NavPoint > {
  static const char* value()
  {
    return "631fef18d2de8d39c6b202102f6ea8dd";
  }

  static const char* value(const ::rob1514::NavPoint&) { return value(); }
};

template<>
struct DataType< ::rob1514::NavPoint > {
  static const char* value()
  {
    return "rob1514/NavPoint";
  }

  static const char* value(const ::rob1514::NavPoint&) { return value(); }
};


// service_traits::MD5Sum< ::rob1514::NavPointRequest> should match 
// service_traits::MD5Sum< ::rob1514::NavPoint > 
template<>
struct MD5Sum< ::rob1514::NavPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rob1514::NavPoint >::value();
  }
  static const char* value(const ::rob1514::NavPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rob1514::NavPointRequest> should match 
// service_traits::DataType< ::rob1514::NavPoint > 
template<>
struct DataType< ::rob1514::NavPointRequest>
{
  static const char* value()
  {
    return DataType< ::rob1514::NavPoint >::value();
  }
  static const char* value(const ::rob1514::NavPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rob1514::NavPointResponse> should match 
// service_traits::MD5Sum< ::rob1514::NavPoint > 
template<>
struct MD5Sum< ::rob1514::NavPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rob1514::NavPoint >::value();
  }
  static const char* value(const ::rob1514::NavPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rob1514::NavPointResponse> should match 
// service_traits::DataType< ::rob1514::NavPoint > 
template<>
struct DataType< ::rob1514::NavPointResponse>
{
  static const char* value()
  {
    return DataType< ::rob1514::NavPoint >::value();
  }
  static const char* value(const ::rob1514::NavPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROB1514_MESSAGE_NAVPOINT_H
