// Generated by gencpp from file rob1514/NavPointRequest.msg
// DO NOT EDIT!


#ifndef ROB1514_MESSAGE_NAVPOINTREQUEST_H
#define ROB1514_MESSAGE_NAVPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rob1514
{
template <class ContainerAllocator>
struct NavPointRequest_
{
  typedef NavPointRequest_<ContainerAllocator> Type;

  NavPointRequest_()
    : x(0.0)
    , y(0.0)
    , r0(0.0)
    , r1(0.0)
    , r2(0.0)
    , r3(0.0)  {
    }
  NavPointRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , r0(0.0)
    , r1(0.0)
    , r2(0.0)
    , r3(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _r0_type;
  _r0_type r0;

   typedef double _r1_type;
  _r1_type r1;

   typedef double _r2_type;
  _r2_type r2;

   typedef double _r3_type;
  _r3_type r3;





  typedef boost::shared_ptr< ::rob1514::NavPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rob1514::NavPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NavPointRequest_

typedef ::rob1514::NavPointRequest_<std::allocator<void> > NavPointRequest;

typedef boost::shared_ptr< ::rob1514::NavPointRequest > NavPointRequestPtr;
typedef boost::shared_ptr< ::rob1514::NavPointRequest const> NavPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rob1514::NavPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rob1514::NavPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rob1514

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rob1514::NavPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rob1514::NavPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rob1514::NavPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rob1514::NavPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rob1514::NavPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rob1514::NavPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rob1514::NavPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7c5a18d8fa4f7649a2e4b1ab86d3972";
  }

  static const char* value(const ::rob1514::NavPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7c5a18d8fa4f764ULL;
  static const uint64_t static_value2 = 0x9a2e4b1ab86d3972ULL;
};

template<class ContainerAllocator>
struct DataType< ::rob1514::NavPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rob1514/NavPointRequest";
  }

  static const char* value(const ::rob1514::NavPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rob1514::NavPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 r0\n\
float64 r1\n\
float64 r2\n\
float64 r3\n\
";
  }

  static const char* value(const ::rob1514::NavPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rob1514::NavPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.r0);
      stream.next(m.r1);
      stream.next(m.r2);
      stream.next(m.r3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rob1514::NavPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rob1514::NavPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "r0: ";
    Printer<double>::stream(s, indent + "  ", v.r0);
    s << indent << "r1: ";
    Printer<double>::stream(s, indent + "  ", v.r1);
    s << indent << "r2: ";
    Printer<double>::stream(s, indent + "  ", v.r2);
    s << indent << "r3: ";
    Printer<double>::stream(s, indent + "  ", v.r3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROB1514_MESSAGE_NAVPOINTREQUEST_H
